services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hover-iot
      PGDATA: /var/lib/data/postgres
    volumes:
      - db:/var/lib/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  vault:
    container_name: hover-iot-vault
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - 8200:8200
networks:
  db:
    driver: bridge
volumes:
  db: