spring:
  config:
    import: bootstrap.yml, application-cst.properties
  datasource:
    url: ${database_uri}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    vault:
      enabled: true