server:
  port: 8080

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
  main:
    web-application-type: servlet