CREATE TABLE TBL_USER
(
    id       BIGSERIAL PRIMARY KEY,
    name     TEXT        NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT        NOT NULL
);

CREATE TABLE TBL_USER_TOKEN
(
    user_id SERIAL PRIMARY KEY,
    tokens  TEXT NOT NULL,
    CONSTRAINT USER_TOKENS_FK FOREIGN KEY (user_id) REFERENCES TBL_USER (id) ON DELETE CASCADE
);