name: CI Build Hover Core

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: atlas
          POSTGRES_PASSWORD: password
          POSTGRES_DB: hover-iot
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit Tests with Maven
        run: mvn -ntp -B verify
